thailand = Country.create(name: "Thailand",continent: "Asia")
antartica = Country.create(name: "Antartica",continent: "Antartica")
uk = Country.create(name: "United Kingdom",continent: "Europe")
brasil = Country.create(name: "Brasil",continent: "South America")
united_states = Country.create(name: "United States of America", continent: "North America")
egypt = Country.create(name: "Egypt",continent: "Africa")
australia = Country.create(name: "Australia",continent: "Australia")
india = Country.create(name: "India",continent: "Asia")
netherlands = Country.create(name: "The Netherlands",continent: "Europe")
france = Country.create(name: "France",continent: "Europe")
guyana = Country.create(name: "Guyana",continent: "South America")
canada = Country.create(name: "Canada",continent: "North America")
tanzania = Country.create(name: "Tanzania",continent: "Africa")

sport = Category.create(name: "Sports")
nature = Category.create(name: "Nature")
museums = Category.create(name: "Museums")
architecture = Category.create(name: "Architecture")

brazilian_jiu_jitsu = Attraction.create(name: "Brazilian Jiu Jitsu",country_id: 4,category_id: 1,meal_included: "false",family_friendly: "true",price: "5.0")
muay_thai = Attraction.create(name: "Muay Thai",country_id: 1,category_id: 1,meal_included: "false",family_friendly: "false",price: "8.0")
ice_hockey = Attraction.create(name: "Ice Hockey Game",country_id: 12,category_id: 1,meal_included: "true",family_friendly: "true",price: "15.0")
cricket = Attraction.create(name: "Cricket Match",country_id: 8,category_id: 1,meal_included: "false",family_friendly: "true",price: "10.0")
polar_plunge = Attraction.create(name: "Polar Plunge",country_id: 2,category_id: 1,meal_included: "false",family_friendly: "false",price: "5.0")
basketball = Attraction.create(name: "Basketball Game",country_id: 5,category_id: 1,meal_included: "true",family_friendly: "true",price: "15.0")
opera = Attraction.create(name:"Manaus Opera House",country_id: 11,category_id: 4,meal_included: "false",family_friendly: "true",price: "0.0")


amazon = Attraction.create(name: "Amazon Jungle",country_id: 4,category_id: 2,meal_included: "false",family_friendly: "true",price: "0.0")
volcanic_bath = Attraction.create(name: "Volcanic Bath at Deception Island",country_id: 2,category_id: 2,meal_included: "true",family_friendly: "false",price: "20.0")
kangaroo = Attraction.create(name: "Kangaroo Sanctuary",country_id: 7,category_id: 2,meal_included: "true",family_friendly: "true",price: "12.0")
mount_kilimanjaro = Attraction.create(name: "Mount Kilimanjaro",country_id: 13,category_id: 2,meal_included: "false",family_friendly: "false",price: "7.0")
grand_canyon = Attraction.create(name: "Grand Canyon",country_id: 5,category_id: 2,meal_included: "false",family_friendly: "true",price: "0.0")
kaieteur_falls = Attraction.create(name: "Kaieteur Falls",country_id: 11,category_id: 2,meal_included: "false",family_friendly: "true",price: "11.0")

madame_tussands = Attraction.create(name: "Madame Tussands London",country_id: 3,category_id: 3,meal_included: "true",family_friendly: "true",price: "10.0")
van_gogh = Attraction.create(name: "Van Gogh Museum",country_id: 9,category_id: 3,meal_included: "false",family_friendly: "true",price: "5.0")
louvre = Attraction.create(name: "The Louvre",country_id: 10,category_id: 3,meal_included: "false",family_friendly: "true",price: "5.0")
egyptian_museum = Attraction.create(name: "The Egyptian Museum",country_id: 6,category_id: 3,meal_included: "false",family_friendly: "true",price: "8.0")
childrens_museum = Attraction.create(name: "Childrens Museum",country_id: 5,category_id: 3,meal_included: "true",family_friendly: "true",price: "7.0")
powerhouse = Attraction.create(name: "Powerhouse Museum",country_id: 7,category_id: 3,meal_included: "false",family_friendly: "true",price: "0.0")

eiffel_tower = Attraction.create(name: "The Eiffel Tower",country_id: 10,category_id: 4,meal_included: "false",family_friendly: "true",price: "10.0")
cube_house = Attraction.create(name: "Cube Houses",country_id: 9,category_id: 4,meal_included: "false",family_friendly: "true",price: "0.0")
taj_mahal = Attraction.create(name: "The Taj Mahal",country_id: 8,category_id: 4,meal_included: "false",family_friendly: "true",price: "0.0")
pyramid = Attraction.create(name: "Egyptian Pyramids",country_id: 6,category_id: 4,meal_included: "false",family_friendly: "true",price: "8.0")
buddha_temple = Attraction.create(name: "Budda Temples",country_id: 1,category_id: 4,meal_included: "false",family_friendly: "true",price: "0.0")
kings_cross = Attraction.create(name: "King's Cross",country_id: 3,category_id: 4,meal_included: "false",family_friendly: "true",price: "0.0")
